### ISSUE TITLE
Deprecated this pkg

### ISSUE THREAD

**Issue by GitScrum** [michael-ciniawsky/posthtml-preset-html#4]
Need deprecated this pkg e.g. this pkg migrate to posthtml-standard

**Comment by michael-ciniawsky** [comment]
yep this preset is crap anyways, was just for testing posthtml-load-presets approach, sry for the delay i don't get notifications for this repo. Nice work with posthtml-beautify, a candidate for a core plugin 👍, but i don't want to stress you here again 👯 :)

**Comment by GitScrum** [comment]
@michael-ciniawsky 
>Nice work with posthtml-beautify
thanks 👍
